### ISSUE TITLE
Enable multi-word searches within bolded stuff (e.g. ^b^‘‘rassadīghādinā’’^eb^)

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#298]
AC:
- [x] search phrases that span across bolded and unbolded words display in search results

**Comment by bdhrs** [comment]
**coro** nāma yo - another good test

**Comment by bdhrs** [comment]
when searching, specifically in aṭṭhakaṭhā and ṭīkā, there are many **bolded** words (which correspond to the word being commented on in the mūḷa). currently, if a search phrase spans across the bolded and unbolded parts, search results will be 0.

example: search in aṭṭhakathā for "anuttaraṃ santivarapad". that gets found. but searching for   "anuttaraṃ santivarapadanti" does not cos the html is santivarapada</b>nti

**Comment by MaxxJohnson** [comment]
AC:
- [ ] search phrases that span across bolded and unbolded words display in search results

**Comment by rrogowski** [comment]
V @bdhrs @parthopdas As an FYI, I think this is an issue in both the "Search" and "Dictionary" features. I just merged some code to address this problem in the Search feature. I can take a look at the Dictionary feature next.

**Comment by parthopdas** [comment]
yeah there is a separate item for that - i'll speak to you about it and you can pick that up as well

unless, this issue is not fixed and / or there is a related regression - please move on. just so we dont deal with too many "issues" in 1 issue.
